# fly.toml app configuration file generated for mbailey-emailer-service on 2024-09-11T14:22:45-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'mbailey-emailer-service'
primary_region = 'mia'

[build]

[http_service]
  internal_port = 4000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[env]

  #-----main config------
  CURRENT_PORT = "4000"
  NODE_DEBUG="email-templates node app.js"
  EMAILER_SERVICE_PASSWORD="ymbwquvjkxqhooxg"
  EMAILER_SERVICE_EMAIL="gnbcjapaneseclass3@gmail.com"
  #-----main config------

  #----firebse config for hashing DB----
  FIREBASE_API_KEY="AIzaSyDzjD9ueA9OiTvCWeICq6pILqSWSfOdG6A"
  FIREBASE_PORT="apanese-class-hashes.firebaseapp.com"
  DATABASE_URL="https://japanese-class-hashes-default-rtdb.firebaseio.com"
  FIREBASE_MESSAGE_SENDER_ID="20392315569"
  FIREBASE_APP_ID="1:20392315569:web:9c2d5fdde498defb17f090"
  FIREBASE_MEASUREMENT_ID="G-CXX0MC44MF"
  EMAIL_UNSUBSCRIBE_LINK="https://script.google.com/macros/s/AKfycbx2QiyUkrzl5SP5YX_ENDWtK53-7f2a056we2mSb4ZAysmPYwcHKc7dFXIQ_Jt3SApOqA/exec"
  #----firebse config for hashing DB----

[[vm]]
  memory = '8gb'
  cpu_kind = 'shared'
  cpus = 2

