const EMAIL_MESSENGER_EVENT_QUEUE_NAME = "emailerQueue";
const ERROR_MESSENGER_EVENT_QUEUE_NAME = "errorQueue";

module.exports ={
    EMAIL_MESSENGER_EVENT_QUEUE_NAME,
    ERROR_MESSENGER_EVENT_QUEUE_NAME
};