const TEMPLATE_CREATOR_EVENT_QUEUE_NAME = "templateCreationQueue";
const TEMPLATE_UPDATER_EVENT_QUEUE_NAME = "templateUpdateQueue";
const TEMPLATE_DELETER_EVENT_QUEUE_NAME = "templateDeleteQueue";
const TEMPLATE_GETTER_EVENT_QUEUE_NAME = "templateGetterQueue";
const ERROR_MESSENGER_EVENT_QUEUE_NAME = "errorQueue";

module.exports ={
    TEMPLATE_CREATOR_EVENT_QUEUE_NAME,
    TEMPLATE_UPDATER_EVENT_QUEUE_NAME,
    TEMPLATE_DELETER_EVENT_QUEUE_NAME,
    TEMPLATE_GETTER_EVENT_QUEUE_NAME,
    ERROR_MESSENGER_EVENT_QUEUE_NAME
};